# Generated by Django 5.0.2 on 2024-02-20 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproducto', models.IntegerField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.productos')),
            ],
        ),
    ]
