# Generated by Django 5.0.2 on 2024-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo_productos',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
