# Generated by Django 5.0.2 on 2024-03-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_productos_codigo_productos_delete_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('id_producto',)},
        ),
    ]
